export const AUDIT_ACTIONS = [
  "USER_CREATED",
  "USER_UPDATED",
  "USER_DELETED",
  "USER_LOGGED_IN",
  "USER_LOGGED_OUT",
  "USER_PASSWORD_CHANGED",
  "USER_PASSWORD_RESET",
  "USER_LOCKED",
  "USER_UNLOCKED",
  "USER_ACTIVATED",
  "USER_DEACTIVATED",
  "ROLE_CREATED",
  "ROLE_UPDATED",
  "ROLE_DELETED",
  "PERMISSION_CREATED",
  "PERMISSION_UPDATED",
  "PERMISSION_DELETED",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
